export const ingredients = [
    { id: 5, name: "Egg White", category: "Eggs", rank: 2 },
    { id: 6, name: "Egg Yolk", category: "Eggs", rank: 0 },
    { id: 7, name: "Eggs (Chicken Egg / Whole Egg)", category: "Eggs", rank: 2 },
    { id: 8, name: "Quail Eggs", category: "Eggs", rank: 0 },
    { id: 10, name: "Blue Cheeses / Mold Cheeses", category: "Dairy Products", rank: 2 },
    { id: 11, name: "Butter: Cultured Butter, Mildly Soured Butter", category: "Dairy Products", rank: 1 },
    { id: 12, name: "Butter: Sweet Cream Butter", category: "Dairy Products", rank: 0 },
    { id: 13, name: "Butterkaese", category: "Dairy Products", rank: 0 },
    { id: 14, name: "Buttermilk (slighltly sour, starting to ferment)", category: "Dairy Products", rank: 1 },
    { id: 15, name: "Cheddar Cheese", category: "Dairy Products", rank: 2 },
    { id: 16, name: "Cheese made from unpasteurised 'raw' milk", category: "Dairy Products", rank: 2 },
    { id: 17, name: "Cheese: Hard cheese, all well matured cheeses", category: "Dairy Products", rank: 3 },
    { id: 18, name: "Cream Cheeses (means: 'very young cheeses'), plain, without additives", category: "Dairy Products", rank: 0 },
    { id: 19, name: "Cream, sweet, without additives", category: "Dairy Products", rank: 0 },
    { id: 20, name: "Curd Cheese", category: "Dairy Products", rank: 0 },
    { id: 21, name: "Ewe's milk / Sheep's milk", category: "Dairy Products", rank: 0 },
    { id: 22, name: "Farmer's cheese (a type of fresh cheese)", category: "Dairy Products", rank: 0 },
    { id: 23, name: "Feta Cheese", category: "Dairy Products", rank: 0 },
    { id: 24, name: "Fontina cheese", category: "Dairy Products", rank: 2 },
    { id: 25, name: "Geheimratskaese, Geheimrats cheese", category: "Dairy Products", rank: 0 },
    { id: 26, name: "Goat's milk / Goat milk", category: "Dairy Products", rank: 0 },
    { id: 27, name: "Gouda cheese (young)", category: "Dairy Products", rank: 0 },
    { id: 28, name: "Gouda cheese (old)", category: "Dairy Products", rank: 2 },
    { id: 29, name: "Kefir / Keefir / Kephir", category: "Dairy Products", rank: 1 },
    { id: 30, name: "Mascarpone Cheese", category: "Dairy Products", rank: 0 },
    { id: 31, name: "Milk (Lactose-free)", category: "Dairy Products", rank: 1 },
    { id: 32, name: "Milk (Pasteurised)", category: "Dairy Products", rank: 0 },
    { id: 33, name: "Milk (UHT)", category: "Dairy Products", rank: 0 },
    { id: 34, name: "Milkpowder", category: "Dairy Products", rank: 1 },
    { id: 35, name: "Mold Cheeses / Mould Cheeses", category: "Dairy Products", rank: 2 },
    { id: 36, name: "Mozzarella cheese", category: "Dairy Products", rank: 0 },
    { id: 37, name: "Processed cheese", category: "Dairy Products", rank: 2 },
    { id: 38, name: "Products made from unprocessed (raw) milk", category: "Dairy Products", rank: 2 },
    { id: 39, name: "Quark", category: "Dairy Products", rank: 0 },
    { id: 40, name: "Raclette cheese", category: "Dairy Products", rank: 2 },
    { id: 41, name: "Raw Milk", category: "Dairy Products", rank: 0 },
    { id: 42, name: "Ready made cheese preparations (with other/further ingredients)", category: "Dairy Products", rank: 2 },
    { id: 43, name: "Ricotta cheese", category: "Dairy Products", rank: 0 },
    { id: 44, name: "Rochefort Cheese / Roquefort Cheese", category: "Dairy Products", rank: 2 },
    { id: 46, name: "Sheep's milk", category: "Dairy Products", rank: 0 },
    { id: 47, name: "Sourcream", category: "Dairy Products", rank: 1 },
    { id: 48, name: "Whey", category: "Dairy Products", rank: 0 },
    { id: 49, name: "Yoghurt (Natural Yoghurt)", category: "Dairy Products", rank: 1 },
    { id: 50, name: "Beef (Fresh)", category: "Meat", rank: 0 },
    { id: 51, name: "Chicken", category: "Meat", rank: 0 },
    { id: 52, name: "Dried Meat (Any Kind)", category: "Meat", rank: 3 },
    { id: 53, name: "Dry-cured ham", category: "Meat", rank: 3 },
    { id: 54, name: "Duck", category: "Meat", rank: 0 },
    { id: 55, name: "Entrails", category: "Meat", rank: 2 },
    { id: 56, name: "Game", category: "Meat", rank: 1 },
    { id: 57, name: "Ham (Dried / Cured)", category: "Meat", rank: 3 },
    { id: 58, name: "Innards", category: "Meat", rank: 2 },
    { id: 59, name: "Minced Meat (If eaten immediately after its production)", category: "Meat", rank: 0 },
    { id: 60, name: "Minced Meat (Open Sale or pre-packed)", category: "Meat", rank: 2 },
    { id: 61, name: "Ostrich", category: "Meat", rank: 0 },
    { id: 62, name: "Pork (Fresh & Untreated)", category: "Meat", rank: 1 },
    { id: 63, name: "Poultry Meat", category: "Meat", rank: 0 },
    { id: 64, name: "Quail", category: "Meat", rank: 0 },
    { id: 65, name: "Salami", category: "Meat", rank: 3 },
    { id: 66, name: "Sausages (All Kinds)", category: "Meat", rank: 3 },
    { id: 67, name: "Smoked Fish (Any)", category: "Meat", rank: 3 },
    { id: 68, name: "Smoked Meat (Any)", category: "Meat", rank: 3 },
    { id: 69, name: "Tongue", category: "Meat", rank: 0 },
    { id: 70, name: "Turkey", category: "Meat", rank: 0 },
    { id: 71, name: "Veal (Fresh)", category: "Meat", rank: 0 },
    { id: 1, name: "Venison", category: "Meat", rank: 1 },
    { id: 72, name: "Wild Meat", category: "Meat", rank: 1 },
    { id: 73, name: "Anchovies", category: "Fish", rank: 3 },
    { id: 74, name: "Fish (Fresh Caught / Frozen)", category: "Fish", rank: 0 },
    { id: 75, name: "Fish (In the shop in the cooling rack or on ice)", category: "Fish", rank: 3 },
    { id: 76, name: "Trout (Freshwater: Brown, Brook, Rainbow trout)", category: "Fish", rank: 0 },
    { id: 77, name: "Tuna", category: "Fish", rank: 3 },
    { id: 78, name: "Bivalves (Mussels, oysters, clams, scallops, etc)", category: "Seafood", rank: 2 },
    { id: 79, name: "Crab", category: "Seafood", rank: 2 },
    { id: 80, name: "Crawfish", category: "Seafood", rank: 2 },
    { id: 81, name: "Crayfish", category: "Seafood", rank: 2 },
    { id: 82, name: "Langouste", category: "Seafood", rank: 2 },
    { id: 83, name: "Lobster", category: "Seafood", rank: 2 },
    { id: 84, name: "Oysters", category: "Seafood", rank: 2 },
    { id: 85, name: "Prawn", category: "Seafood", rank: 2 },
    { id: 86, name: "Rock Lobsters", category: "Seafood", rank: 2 },
    { id: 87, name: "Shellfish", category: "Seafood", rank: 2 },
    { id: 88, name: "Shrimp", category: "Seafood", rank: 2 },
    { id: 89, name: "Spiny Lobsters", category: "Seafood", rank: 2 },
    { id: 90, name: "Lard", category: "Miscellaneous", rank: 0 },
    { id: 91, name: "Amaranth / Amaranthus", category: "Starch", rank: 0 },
    { id: 92, name: "Baked Goods", category: "Starch", rank: 1 },
    { id: 93, name: "Barley", category: "Starch", rank: 1 },
    { id: 94, name: "Barley Malt / Malt", category: "Starch", rank: 2 },
    { id: 95, name: "Bread", category: "Starch", rank: 1 },
    { id: 96, name: "Buckwheat", category: "Starch", rank: 2 },
    { id: 97, name: "Chestnut / Sweet Chestnut", category: "Starch", rank: 0 },
    { id: 98, name: "Cornflakes (If no additives such as malt or folic acide)", category: "Starch", rank: 0 },
    { id: 99, name: "Hemp Seeds (Cannabis sativa)", category: "Starch", rank: 0 },
    { id: 100, name: "KAMUT / Khorasan wheat", category: "Starch", rank: 0 },
    { id: 101, name: "Oriental Wheat (Triticum turgidum ssp. turanicum)", category: "Starch", rank: 0 },
    { id: 102, name: "Maltodextrin", category: "Starch", rank: 0 },
    { id: 103, name: "Millet", category: "Starch", rank: 0 },
    { id: 104, name: "Oats", category: "Starch", rank: 0 },
    { id: 105, name: "Pearl Sago", category: "Starch", rank: 0 },
    { id: 106, name: "Potato (With Peel)", category: "Starch", rank: 0 },
    { id: 107, name: "Potato (New, With Peel)", category: "Starch", rank: 0 },
    { id: 108, name: "Potato (Peeled)", category: "Starch", rank: 0 },
    { id: 109, name: "Quinoa", category: "Starch", rank: 0 },
    { id: 110, name: "Rice", category: "Starch", rank: 0 },
    { id: 111, name: "Rice biscuits / Rice cakes", category: "Starch", rank: 0 },
    { id: 112, name: "Rice Crispies", category: "Starch", rank: 0 },
    { id: 113, name: "Rice Noodles", category: "Starch", rank: 0 },
    { id: 114, name: "Rye", category: "Starch", rank: 1 },
    { id: 115, name: "Sago", category: "Starch", rank: 0 },
    { id: 116, name: "Spelt", category: "Starch", rank: 0 },
    { id: 117, name: "Sunflower Seeds", category: "Starch", rank: 2 },
    { id: 118, name: "Sweet Corn / Maize Kernels (corn on the cob / fresh / pasteurised)", category: "Starch", rank: 0 },
    { id: 119, name: "Sweet Corn / Maize Kernels (Dried / Maize Meal / Maize Flour)", category: "Starch", rank: 0 },
    { id: 120, name: "Sweet Corn / Maize Kernels (Out of the Tin)", category: "Starch", rank: 0 },
    { id: 121, name: "Sweet Potato", category: "Starch", rank: 0 },
    { id: 122, name: "Wheat", category: "Starch", rank: 1 },
    { id: 123, name: "Wheat Germ", category: "Starch", rank: 2 },
    { id: 124, name: "wild Rice", category: "Starch", rank: 0 },
    { id: 125, name: "Yam", category: "Starch", rank: 0 },
    { id: 126, name: "Almond", category: "Nuts", rank: 1 },
    { id: 127, name: "Brazil Nut", category: "Nuts", rank: 0 },
    { id: 128, name: "Cashew Nut", category: "Nuts", rank: 1 },
    { id: 129, name: "Chufa Sedge (Cyperus esculentus)", category: "Nuts", rank: 0 },
    { id: 130, name: "Roasted Chufa Sedge (Cyperus esculentus)", category: "Nuts", rank: 2 },
    { id: 131, name: "Earth Almond", category: "Nuts", rank: 0 },
    { id: 132, name: "Hazelnut", category: "Nuts", rank: 1 },
    { id: 133, name: "Macadamia", category: "Nuts", rank: 0 },
    { id: 134, name: "Nut Grass", category: "Nuts", rank: 0 },
    { id: 135, name: "Nuts", category: "Nuts", rank: 3 },
    { id: 136, name: "Peanuts", category: "Nuts", rank: 2 },
    { id: 137, name: "Pine Nuts", category: "Nuts", rank: 1 },
    { id: 138, name: "Pistachio", category: "Nuts", rank: 0 },
    { id: 139, name: "Tiger Nut Sedge", category: "Nuts", rank: 0 },
    { id: 140, name: "Walnut", category: "Nuts", rank: 3 },
    { id: 141, name: "Yellow Nutsedge", category: "Nuts", rank: 0 },
    { id: 142, name: "Black Caraway Oil (Nigella sativa)", category: "Fats and Oils", rank: 0 },
    { id: 143, name: "Canola Oil", category: "Fats and Oils", rank: 0 },
    { id: 144, name: "Coconut Fat / Coconut Oil / Copra Oil", category: "Fats and Oils", rank: 0 },
    { id: 145, name: "Fennel Flower Oil (Nigella sativa)", category: "Fats and Oils", rank: 0 },
    { id: 146, name: "Margarine (check for intolerated additives)", category: "Fats and Oils", rank: 0 },
    { id: 147, name: "Nigella sativa oil", category: "Fats and Oils", rank: 0 },
    { id: 148, name: "Nutmeg Flower Oil (Nigella sativa)", category: "Fats and Oils", rank: 0 },
    { id: 149, name: "Olive Oil", category: "Fats and Oils", rank: 0 },
    { id: 150, name: "Palm Kernel Oil", category: "Fats and Oils", rank: 0 },
    { id: 151, name: "Palm Oil / Dende Oil", category: "Fats and Oils", rank: 0 },
    { id: 152, name: "Pumpkin Seed Oil", category: "Fats and Oils", rank: 0 },
    { id: 153, name: "Rape Seed Oil", category: "Fats and Oils", rank: 0 },
    { id: 154, name: "Roman coriander oil (Nigella sativa)", category: "Fats and Oils", rank: 0 },
    { id: 155, name: "Safflower oil", category: "Fats and Oils", rank: 0 },
    { id: 156, name: "Sunflower oil", category: "Fats and Oils", rank: 1 },
    { id: 157, name: "Walnut Oil", category: "Fats and Oils", rank: 2 },
    { id: 158, name: "Artichoke", category: "Vegetables", rank: 0 },
    { id: 159, name: "Asparagus", category: "Vegetables", rank: 0 },
    { id: 160, name: "Aubergine", category: "Vegetables", rank: 2 },
    { id: 162, name: "Bamboo Shoots", category: "Vegetables", rank: 5 },
    { id: 163, name: "Beans (pulses)", category: "Vegetables", rank: 2 },
    { id: 164, name: "Beetroot", category: "Vegetables", rank: 0 },
    { id: 165, name: "Bell Pepper (Hot)", category: "Vegetables", rank: 2 },
    { id: 166, name: "Bell Pepper (Sweet)", category: "Vegetables", rank: 0 },
    { id: 167, name: "Bok Choi", category: "Vegetables", rank: 0 },
    { id: 168, name: "Borlotti Beans", category: "Vegetables", rank: 2 },
    { id: 169, name: "Brussel Sprouts", category: "Vegetables", rank: 1 },
    { id: 170, name: "Cabbage (Green or White)", category: "Vegetables", rank: 0 },
    { id: 171, name: "Cabbage (Excepting Cauliflower & Kohlrabi", category: "Vegetables", rank: 0 },
    { id: 172, name: "Carrot", category: "Vegetables", rank: 0 },
    { id: 173, name: "Cauliflower", category: "Vegetables", rank: 0 },
    { id: 174, name: "Celery", category: "Vegetables", rank: 0 },
    { id: 175, name: "Celery Cabbage (Brassica rapa subsp. pekinensis)", category: "Vegetables", rank: 0 },
    { id: 176, name: "Chard Stalks (Beta vulgaris subsp. vulgaris)", category: "Vegetables", rank: 1 },
    { id: 177, name: "Chayote", category: "Vegetables", rank: 5 },
    { id: 178, name: "Chickpeas", category: "Vegetables", rank: 2 },
    { id: 179, name: "Chicory (Cichorium intybus)", category: "Vegetables", rank: 0 },
    { id: 180, name: "Chili Pepper (Red, fresh)", category: "Vegetables", rank: 2 },
    { id: 181, name: "Choko", category: "Vegetables", rank: 5 },
    { id: 182, name: "Corn Salad / Lamb's Lettuce (Valerianella locusta)", category: "Vegetables", rank: 0 },
    { id: 183, name: "Courgette", category: "Vegetables", rank: 0 },
    { id: 184, name: "Cress: Garden Cress (Lepidium sativum)", category: "Vegetables", rank: 5 },
    { id: 185, name: "Cucumber", category: "Vegetables", rank: 0 },
    { id: 186, name: "Eggplant", category: "Vegetables", rank: 2 },
    { id: 187, name: "Endive (Cichorium endivia)", category: "Vegetables", rank: 0 },
    { id: 188, name: "Fennel", category: "Vegetables", rank: 0 },
    { id: 189, name: "Garden Cress (Lepidium sativum)", category: "Vegetables", rank: 5 },
    { id: 190, name: "Garlic", category: "Vegetables", rank: 1 },
    { id: 191, name: "German turnip", category: "Vegetables", rank: 1 },
    { id: 192, name: "Gourds", category: "Vegetables", rank: 0 },
    { id: 193, name: "Green beans", category: "Vegetables", rank: 1 },
    { id: 194, name: "Green peas", category: "Vegetables", rank: 1 },
    { id: 195, name: "Green split peas", category: "Vegetables", rank: 1 },
    { id: 196, name: "Horseradish", category: "Vegetables", rank: 1 },
    { id: 197, name: "Kelp", category: "Vegetables", rank: 2 },
    { id: 198, name: "Kohlrabi", category: "Vegetables", rank: 1 },
    { id: 199, name: "Leek", category: "Vegetables", rank: 1 },
    { id: 200, name: "Lentils", category: "Vegetables", rank: 2 },
    { id: 201, name: "Lettuce (Iceberg)", category: "Vegetables", rank: 0 },
    { id: 202, name: "Lettuce (Head & Leaf lettuces)", category: "Vegetables", rank: 0 },
    { id: 203, name: "Marrow", category: "Vegetables", rank: 0 },
    { id: 204, name: "Mungbeans (Germinated, sprouting)", category: "Vegetables", rank: 5 },
    { id: 205, name: "Napa Cabbage", category: "Vegetables", rank: 0 },
    { id: 206, name: "Olives", category: "Vegetables", rank: 2 },
    { id: 207, name: "Onion", category: "Vegetables", rank: 1 },
    { id: 208, name: "Pak Choi", category: "Vegetables", rank: 0 },
    { id: 209, name: "Parsnip", category: "Vegetables", rank: 0 },
    { id: 210, name: "Perennial wall-rocket (Diplotaxis tenuifolia)", category: "Vegetables", rank: 2 },
    { id: 211, name: "Pickled cabbage", category: "Vegetables", rank: 3 },
    { id: 212, name: "Pickled Cucumber", category: "Vegetables", rank: 2 },
    { id: 213, name: "Pickled Gherkin", category: "Vegetables", rank: 2 },
    { id: 214, name: "Pickled Vegetables", category: "Vegetables", rank: 2 },
    { id: 215, name: "Pulses (Soy, Beans, Peas, Lentils, etc)", category: "Vegetables", rank: 2 },
    { id: 216, name: "Pumpkins", category: "Vegetables", rank: 0 },
    { id: 217, name: "Radish (Red & White)", category: "Vegetables", rank: 0 },
    { id: 218, name: "Red Cabbage", category: "Vegetables", rank: 0 },
    { id: 219, name: "Sauerkraut", category: "Vegetables", rank: 3 },
    { id: 220, name: "Savoy Cabbage", category: "Vegetables", rank: 1 },
    { id: 221, name: "Snow Peas", category: "Vegetables", rank: 1 },
    { id: 222, name: "Soy (Soy beans / Soy flour)", category: "Vegetables", rank: 2 },
    { id: 223, name: "Spinach", category: "Vegetables", rank: 2 },
    { id: 224, name: "Squashes", category: "Vegetables", rank: 0 },
    { id: 225, name: "Stinging Nettle (Urtica dioica)", category: "Vegetables", rank: 2 },
    { id: 226, name: "Tomato", category: "Vegetables", rank: 2 },
    { id: 227, name: "Turnip", category: "Vegetables", rank: 5 },
    { id: 228, name: "Turnip Cabbage", category: "Vegetables", rank: 1 },
    { id: 229, name: "Vicia faba, broad bean", category: "Vegetables", rank: 2 },
    { id: 230, name: "White Onion", category: "Vegetables", rank: 0 },
    { id: 231, name: "Yellow Split Peas", category: "Vegetables", rank: 1 },
    { id: 232, name: "Zucchini", category: "Vegetables", rank: 0 },
    { id: 233, name: "Basil", category: "Herbs", rank: 0 },
    { id: 234, name: "Bear Leek (Allium ursinum)", category: "Herbs", rank: 1 },
    { id: 235, name: "Bear's Garlic (Allium ursinum)", category: "Herbs", rank: 1 },
    { id: 236, name: "Blue Fenugreek (Trigonella caerulea)", category: "Herbs", rank: 2 },
    { id: 237, name: "Broad-leaved garlic (Allium ursinum)", category: "Herbs", rank: 1 },
    { id: 238, name: "Buckrams (Allium ursinum)", category: "Herbs", rank: 1 },
    { id: 239, name: "Chives", category: "Herbs", rank: 1 },
    { id: 240, name: "Clover (trigonella & trifolium species)", category: "Herbs", rank: 2 },
    { id: 241, name: "Dill", category: "Herbs", rank: 1 },
    { id: 242, name: "Fenugreek (Trigonella foenum-graecum)", category: "Herbs", rank: 2 },
    { id: 243, name: "Mint", category: "Herbs", rank: 0 },
    { id: 244, name: "Oregano", category: "Herbs", rank: 0 },
    { id: 245, name: "Parsley", category: "Herbs", rank: 0 },
    { id: 246, name: "Ramsons (Allium ursinum)", category: "Herbs", rank: 1 },
    { id: 247, name: "Rosemary", category: "Herbs", rank: 0 },
    { id: 248, name: "Sage", category: "Herbs", rank: 0 },
    { id: 249, name: "Savory (Satureja hortensis)", category: "Herbs", rank: 0 },
    { id: 250, name: "Trifolium", category: "Herbs", rank: 2 },
    { id: 251, name: "Trigonella", category: "Herbs", rank: 2 },
    { id: 252, name: "Wood Garlic (Allium ursinum)", category: "Herbs", rank: 1 },
    { id: 253, name: "Acerola", category: "Fruits", rank: 0 },
    { id: 254, name: "Acerola Powder", category: "Fruits", rank: 0 },
    { id: 255, name: "Barbados Cherry", category: "Fruits", rank: 0 },
    { id: 256, name: "West Indian Cherry", category: "Fruits", rank: 0 },
    { id: 257, name: "Wild Crepe Myrtle", category: "Fruits", rank: 0 },
    { id: 258, name: "Apple", category: "Fruits", rank: 0 },
    { id: 259, name: "Apple (Golden Delicious)", category: "Fruits", rank: 0 },
    { id: 260, name: "Apricot", category: "Fruits", rank: 0 },
    { id: 261, name: "Aronia (Chokeberries, Red & Black)", category: "Fruits", rank: 5 },
    { id: 262, name: "Asimina triloba", category: "Fruits", rank: 5 },
    { id: 263, name: "Avocado", category: "Fruits", rank: 2 },
    { id: 264, name: "Banana", category: "Fruits", rank: 2 },
    { id: 265, name: "Barbary Fig (Opuntia ficus-indica)", category: "Fruits", rank: 5 },
    { id: 266, name: "Blackberry", category: "Fruits", rank: 0 },
    { id: 267, name: "Blackcurrants", category: "Fruits", rank: 0 },
    { id: 268, name: "Blueberries", category: "Fruits", rank: 0 },
    { id: 269, name: "Boysenberry", category: "Fruits", rank: 5 },
    { id: 270, name: "Cactus Pear (Opuntia ficus-indica)", category: "Fruits", rank: 5 },
    { id: 271, name: "Carambola / Starfruit", category: "Fruits", rank: 0 },
    { id: 272, name: "Cherry", category: "Fruits", rank: 0 },
    { id: 273, name: "Citrus Fruits", category: "Fruits", rank: 2 },
    { id: 274, name: "Cocoa Butter", category: "Fruits", rank: 0 },
    { id: 275, name: "Cocoa / Cocoa Powder (Chocolate, etc)", category: "Fruits", rank: 2 },
    { id: 276, name: "Coconut / Coconut Shavings / Coconut Milk", category: "Fruits", rank: 0 },
    { id: 277, name: "Common Pawpaw of NE USA", category: "Fruits", rank: 5 },
    { id: 278, name: "Common Sea-buckthorn (Hippophae rhamnoides)", category: "Fruits", rank: 0 },
    { id: 279, name: "Cowberry", category: "Fruits", rank: 0 },
    { id: 280, name: "Cranberry", category: "Fruits", rank: 0 },
    { id: 281, name: "Dates (Dried)", category: "Fruits", rank: 0 },
    { id: 282, name: "Dog Rose (Rosa canina)", category: "Fruits", rank: 1 },
    { id: 283, name: "Dragon Fruit / Pitaya / Pitahaya", category: "Fruits", rank: 0 },
    { id: 284, name: "Figs (Fresh or Dried)", category: "Fruits", rank: 1 },
    { id: 285, name: "Goji Berry / Chinese Wolfberry / Chinese Boxthorn / Himalayan goji / Tibetan goji", category: "Fruits", rank: 0 },
    { id: 286, name: "Gooseberry / Gooseberries", category: "Fruits", rank: 0 },
    { id: 287, name: "Grapefruit", category: "Fruits", rank: 2 },
    { id: 288, name: "Grapes", category: "Fruits", rank: 0 },
    { id: 289, name: "Guava", category: "Fruits", rank: 2 },
    { id: 290, name: "Indian fig opuntia (Opuntia ficus-indica)", category: "Fruits", rank: 5 },
    { id: 291, name: "Jostaberry", category: "Fruits", rank: 0 },
    { id: 292, name: "Kaki", category: "Fruits", rank: 0 },
    { id: 293, name: "Kiwi Fruit", category: "Fruits", rank: 2 },
    { id: 294, name: "Ladyfinger Banana", category: "Fruits", rank: 5 },
    { id: 295, name: "Lemon", category: "Fruits", rank: 2 },
    { id: 296, name: "Lemon Peel / Lemon Zest", category: "Fruits", rank: 2 },
    { id: 297, name: "Lime", category: "Fruits", rank: 3 },
    { id: 298, name: "Lingonberry", category: "Fruits", rank: 0 },
    { id: 299, name: "Loganberry", category: "Fruits", rank: 5 },
    { id: 300, name: "Lychee", category: "Fruits", rank: 0 },
    { id: 301, name: "Mandarin Orange (Citrus reticulata)", category: "Fruits", rank: 2 },
    { id: 302, name: "Mango", category: "Fruits", rank: 1 },
    { id: 303, name: "Melons (Except Watermelon)", category: "Fruits", rank: 0 },
    { id: 304, name: "Morella Cherries", category: "Fruits", rank: 0 },
    { id: 305, name: "Mulberry", category: "Fruits", rank: 5 },
    { id: 306, name: "Nashi Pear", category: "Fruits", rank: 5 },
    { id: 307, name: "Nectarine", category: "Fruits", rank: 0 },
    { id: 308, name: "Orange", category: "Fruits", rank: 3 },
    { id: 309, name: "Orange Peel / Orange Zest", category: "Fruits", rank: 3 },
    { id: 310, name: "Papaya / Pawpaw", category: "Fruits", rank: 2 },
    { id: 311, name: "Passion Fruit", category: "Fruits", rank: 5 },
    { id: 312, name: "Peach", category: "Fruits", rank: 0 },
    { id: 313, name: "Pear", category: "Fruits", rank: 1 },
    { id: 314, name: "Pear (peeled, canned in sugar syrup)", category: "Fruits", rank: 1 },
    { id: 315, name: "Persimmon", category: "Fruits", rank: 0 },
    { id: 316, name: "Pineapple", category: "Fruits", rank: 2 },
    { id: 317, name: "Pitaya / Pitahaya / Dragon Fruit", category: "Fruits", rank: 0 },
    { id: 318, name: "Plum", category: "Fruits", rank: 1 },
    { id: 319, name: "Pomegranate", category: "Fruits", rank: 0 },
    { id: 320, name: "Prickly Pear (Opuntia ficus-indica)", category: "Fruits", rank: 5 },
    { id: 321, name: "Prune", category: "Fruits", rank: 1 },
    { id: 322, name: "Prunus domestica subsp. Domestica", category: "Fruits", rank: 1 },
    { id: 323, name: "Purple Granadilla / Passionfruit", category: "Fruits", rank: 5 },
    { id: 324, name: "Quince", category: "Fruits", rank: 0 },
    { id: 325, name: "Raisins", category: "Fruits", rank: 0 },
    { id: 326, name: "Raspberry", category: "Fruits", rank: 2 },
    { id: 327, name: "Redcurrants / Currant", category: "Fruits", rank: 0 },
    { id: 328, name: "Rhubarb", category: "Fruits", rank: 1 },
    { id: 329, name: "Rose Hip", category: "Fruits", rank: 1 },
    { id: 330, name: "Sallow Thorn", category: "Fruits", rank: 0 },
    { id: 331, name: "Sharon Fruit", category: "Fruits", rank: 0 },
    { id: 332, name: "Sour Cherry", category: "Fruits", rank: 0 },
    { id: 333, name: "Spineless Cactus (Opuntia ficus-indica)", category: "Fruits", rank: 5 },
    { id: 334, name: "Strawberry", category: "Fruits", rank: 2 },
    { id: 335, name: "Sugar Banana", category: "Fruits", rank: 5 },
    { id: 336, name: "Tamarillo (Solanum betaceum)", category: "Fruits", rank: 5 },
    { id: 337, name: "Waterlemon", category: "Fruits", rank: 1 },
    { id: 338, name: "Zwetschge", category: "Fruits", rank: 1 },
    { id: 339, name: "Chia (Salvia hispanica)", category: "Seeds", rank: 0 },
    { id: 340, name: "Isabgol / Psyllium seed husks", category: "Seeds", rank: 0 },
    { id: 341, name: "Ispaghula / Psyllium seed husks", category: "Seeds", rank: 0 },
    { id: 342, name: "Psyllium seed husks (Plantago ovata)", category: "Seeds", rank: 0 },
    { id: 343, name: "Pumpkin Seeds", category: "Seeds", rank: 0 },
    { id: 344, name: "Sesame", category: "Seeds", rank: 1 },
    { id: 345, name: "Algae (and algae derivatives)", category: "Mushooms, Fungi, & Algae", rank: 3 },
    { id: 346, name: "Brown Algae", category: "Mushrooms, Fungi, & Algae", rank: 3 },
    { id: 347, name: "Cep", category: "Mushrooms, Fungi, & Algae", rank: 2 },
    { id: 348, name: "Green Algae", category: "Mushrooms, Fungi, & Algae", rank: 3 },
    { id: 349, name: "Kelp / Seaweed", category: "Mushrooms, Fungi, & Algae", rank: 3 },
    { id: 350, name: "Kombu Seaweed", category: "Mushrooms, Fungi, & Algae", rank: 3 },
    { id: 351, name: "Morel", category: "Mushrooms, Fungi, & Algae", rank: 2 },
    { id: 352, name: "Mushrooms", category: "Mushrooms, Fungi, & Algae", rank: 2 },
    { id: 353, name: "Nori seaweed", category: "Mushrooms, Fungi, & Algae", rank: 3 },
    { id: 354, name: "Porcino mushroom (boletus edulis)", category: "Mushrooms, Fungi, & Algae", rank: 2 },
    { id: 355, name: "Red Algae", category: "Mushrooms, Fungi, & Algae", rank: 3 },
    { id: 356, name: "Seaweed / Seaweed Derivitives", category: "Mushrooms, Fungi, & Algae", rank: 3 },
    { id: 357, name: "Wakame Seaweed", category: "Mushrooms, Fungi, & Algae", rank: 3 },
    { id: 358, name: "White Button Mushroom", category: "Mushrooms, Fungi, & Algae", rank: 1 },
    { id: 359, name: "Yeast (Fresh or Dried)", category: "Mushrooms, Fungi, & Algae", rank: 1 },
    { id: 360, name: "Agave Nectar / Agave Syrup", category: "Sweeteners", rank: 0 },
    { id: 361, name: "Artificial Sweeteners", category: "Sweeteners", rank: 1 },
    { id: 362, name: "Birch Sugar / Xylitol / Xylite / E967", category: "Sweeteners", rank: 0 },
    { id: 363, name: "Caramel (Browned Sugar)", category: "Sweeteners", rank: 0 },
    { id: 364, name: "Dextrose", category: "Sweeteners", rank: 0 },
    { id: 365, name: "E420 / Sorbitol / Glucitol", category: "Sweeteners", rank: 0 },
    { id: 366, name: "E967, Xylitol, Xylite, Birch Sugar", category: "Sweeteners", rank: 0 },
    { id: 367, name: "Extract of Malt", category: "Sweeteners", rank: 2 },
    { id: 368, name: "Fructose (Fruit Sugar)", category: "Sweeteners", rank: 0 },
    { id: 369, name: "Glucose", category: "Sweeteners", rank: 0 },
    { id: 370, name: "Honey", category: "Sweeteners", rank: 0 },
    { id: 371, name: "Inverted Sugar Syrup", category: "Sweeteners", rank: 0 },
    { id: 372, name: "Lactose (Milk Sugar)", category: "Sweeteners", rank: 0 },
    { id: 373, name: "Liquorice Root", category: "Sweeteners", rank: 2 },
    { id: 374, name: "Malt Extract", category: "Sweeteners", rank: 2 },
    { id: 375, name: "Maltose / Malt Sugar (Pure)", category: "Sweeteners", rank: 0 },
    { id: 376, name: "Maple Syrup", category: "Sweeteners", rank: 0 },
    { id: 377, name: "Palm Sugar", category: "Sweeteners", rank: 5 },
    { id: 378, name: "Sorbitol / Glucitol / E420", category: "Sweeteners", rank: 0 },
    { id: 379, name: "Stevia (Stevia Leaves, Liquid / Powder)", category: "Sweeteners", rank: 0 },
    { id: 380, name: "Sucrose", category: "Sweeteners", rank: 0 },
    { id: 381, name: "Xylitol / Xylite / Birch Sugar / E967", category: "Sweeteners", rank: 0 },
    { id: 382, name: "Anise / Aniseed", category: "Spices, Seasoning, Aroma", rank: 5 },
    { id: 383, name: "Bay Laurel / Laurel", category: "Spices, Seasoning, Aroma", rank: 5 },
    { id: 384, name: "Black Caraway (Nigella sativa)", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 385, name: "Bouillon", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 386, name: "Caraway (Carum carvi)", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 387, name: "Cardamom", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 388, name: "Cilantro", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 389, name: "Cinnamon", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 390, name: "Cloves", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 391, name: "Coriander", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 392, name: "Cumin (Cuminum cyminum)", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 393, name: "Curry", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 394, name: "Distilled White Vinegar", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 395, name: "Fennel Flower (Nigella sativa)", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 396, name: "Ginger", category: "Spices, Seasoning, Aroma", rank: 1 },
    { id: 397, name: "Jeera", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 398, name: "Juniper Berries", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 399, name: "Meat Extract", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 400, name: "Meridian Fennel (Carum carvi)", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 401, name: "Mustard / Mustard Seeds / Mustardseed Powder", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 402, name: "Nigella sativa seed", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 403, name: "Nutmeg", category: "Spices, Seasoning, Aroma", rank: 1 },
    { id: 404, name: "Nutmeg Flower (Nigella sativa)", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 405, name: "Paprika (Hot)", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 406, name: "Paprika (Sweet)", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 407, name: "Pepper (Black)", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 408, name: "Pepper (White)", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 409, name: "Persian cumin (Carum carvi)", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 410, name: "Poppy Seeds", category: "Spices, Seasoning, Aroma", rank: 1 },
    { id: 411, name: "Red Wine Vinegar", category: "Spices, Seasoning, Aroma", rank: 3 },
    { id: 412, name: "Roman coriander (Nigella sativa)", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 413, name: "Seasoning made w/ hydrolysated proteins", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 414, name: "Soy Sauce", category: "Spices, Seasoning, Aroma", rank: 3 },
    { id: 415, name: "Spirit Vinegar", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 416, name: "Star Anise / Star Anise Seed / Badiam", category: "Spices, Seasoning, Aroma", rank: 5 },
    { id: 417, name: "Thyme", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 418, name: "Tumeric (Curcuma longa)", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 419, name: "Vanilla Extract", category: "Spices, Seasoning, Aroma", rank: 1 },
    { id: 420, name: "Vanila / Vanilla Pod / Vanilla Powder / Vanilla Sugar", category: "Spices, Seasoning, Aroma", rank: 1 },
    { id: 421, name: "Vinegar: Apple Vinegar", category: "Spices, Seasoning, Aroma", rank: 1 },
    { id: 422, name: "Vinegar: Balsalmic Vinegar", category: "Spices, Seasoning, Aroma", rank: 3 },
    { id: 423, name: "Vinegar: Spirit / Distilled White", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 424, name: "Vinegar: White Wine", category: "Spices, Seasoning, Aroma", rank: 0 },
    { id: 425, name: "Yeast Extract", category: "Spices, Seasoning, Aroma", rank: 2 },
    { id: 426, name: "'Healing' Spring water w/ lots of Sulfur, Flourine, Iodine, & Carbonic Acid", category: "Beverages", rank: 1 },
    { id: 427, name: "Mineral Water / Still Water", category: "Beverages", rank: 0 },
    { id: 428, name: "Tap Water", category: "Beverages", rank: 0 },
    { id: 429, name: "Alcohol (Pure / Ethanol)", category: "Beverages", rank: 3 },
    { id: 430, name: "Alcoholic Beverages", category: "Beverages", rank: 3 },
    { id: 431, name: "Beer", category: "Beverages", rank: 2 },
    { id: 432, name: "Brandy", category: "Beverages", rank: 2 },
    { id: 433, name: "Champagne", category: "Beverages", rank: 3 },
    { id: 434, name: "Ethanol", category: "Beverages", rank: 3 },
    { id: 435, name: "Liquor - Clear / Colorless", category: "Beverages", rank: 2 },
    { id: 436, name: "Liquor - Schnapps / Spirits / Cloudy", category: "Beverages", rank: 3 },
    { id: 437, name: "Rum", category: "Beverages", rank: 2 },
    { id: 438, name: "Sparkling Wine", category: "Beverages", rank: 3 },
    { id: 439, name: "Wine", category: "Beverages", rank: 3 },
    { id: 440, name: "Wine (Histamine Free)", category: "Beverages", rank: 1 },
    { id: 441, name: "Wine (Red)", category: "Beverages", rank: 3 },
    { id: 442, name: "Wine (Schilcherwein)", category: "Beverages", rank: 2 },
    { id: 443, name: "Wine (White)", category: "Beverages", rank: 2 },
    { id: 444, name: "Chamomile Tea", category: "Beverages", rank: 0 },
    { id: 445, name: "Green Tea", category: "Beverages", rank: 1 },
    { id: 446, name: "Herbal Teas w/medicinal herbs", category: "Beverages", rank: 1 },
    { id: 447, name: "Lime Blossom Tea", category: "Beverages", rank: 0 },
    { id: 448, name: "Mate Tea (Ilex paraguariensis)", category: "Beverages", rank: 1 },
    { id: 449, name: "Peppermint Tea", category: "Beverages", rank: 0 },
    { id: 450, name: "Rooibos Tea", category: "Beverages", rank: 0 },
    { id: 451, name: "Sage Tea", category: "Beverages", rank: 0 },
    { id: 452, name: "Stinging Nettle Herbal Tea (Urtica dioica)", category: "Beverages", rank: 1 },
    { id: 453, name: "Tea / Black Tea", category: "Beverages", rank: 2 },
    { id: 454, name: "Verbena Herbal Tea", category: "Beverages", rank: 0 },
    { id: 455, name: "Cranberry Nectar", category: "Beverages", rank: 0 },
    { id: 456, name: "Orange Juice", category: "Beverages", rank: 2 },
    { id: 457, name: "Tomato Juice", category: "Beverages", rank: 2 },
    { id: 458, name: "Coca-Cola", category: "Beverages", rank: 1 },
    { id: 459, name: "Coffee", category: "Beverages", rank: 1 },
    { id: 460, name: "Coke", category: "Beverages", rank: 1 },
    { id: 461, name: "Cola-drinks", category: "Beverages", rank: 1 },
    { id: 462, name: "Energy Drinks", category: "Beverages", rank: 2 },
    { id: 463, name: "Espresso", category: "Beverages", rank: 1 },
    { id: 464, name: "Oat Milk", category: "Beverages", rank: 1 },
    { id: 465, name: "Rice Milk", category: "Beverages", rank: 1 },
    { id: 466, name: "Soy Milk", category: "Beverages", rank: 2 },
    { id: 467, name: "Chocolate Drinks", category: "Beverages", rank: 2 },
    { id: 468, name: "Cocoa Drinks", category: "Beverages", rank: 2 },
    { id: 469, name: "Elderflower Cordial", category: "Beverages", rank: 0 },
    { id: 470, name: "Hot Chocolate", category: "Beverages", rank: 2 },
    { id: 471, name: "Lemonade", category: "Beverages", rank: 1 },
    { id: 472, name: "Ovaltine", category: "Beverages", rank: 2 },
    { id: 473, name: "Soda", category: "Beverages", rank: 1 },
    { id: 474, name: "Soft Drinks", category: "Beverages", rank: 1 },
    { id: 475, name: "2-hydroxybiphenyl, E231", category: "Food Additives", rank: 2 },
    { id: 476, name: "Acacia gum / Gum arabic / E414", category: "Food Additives", rank: 1 },
    { id: 477, name: "Acetate of Lime / Calcium Acetate / E262", category: "Food Additives", rank: 0 },
    { id: 478, name: "Acetic Acid / E260", category: "Food Additives", rank: 0 },
    { id: 479, name: "Acid Red 14 / E122", category: "Food Additives", rank: 2 },
    { id: 480, name: "Agar / E406", category: "Food Additives", rank: 1 },
    { id: 481, name: "Alginic Acid / Algin / Alginate / E400", category: "Food Additives", rank: 2 },
    { id: 482, name: "Allura Red / Food Red 17 / CI 16035 / FD&C Red 40 / E129 / 2-Naphthalenesulfonic acid", category: "Food Additives", rank: 2 },
    { id: 483, name: "Alpha-tocopherol / Vitamin E / E307", category: "Food Additives", rank: 0 },
    { id: 484, name: "Aluminum / E173", category: "Food Additives", rank: 5 },
    { id: 485, name: "Amaranth / E123", category: "Food Additives", rank: 2 },
    { id: 486, name: "Ammonia Caramel / E150c", category: "Food Additives", rank: 0 },
    { id: 487, name: "Ammonium Alginate / E403", category: "Food Additives", rank: 2 },
    { id: 488, name: "Ammonium Carbonate / Baker's Ammonia / E503", category: "Food Additives", rank: 0 },
    { id: 489, name: "Ammonium Citrate / Triammonium Citrate / E380", category: "Food Additives", rank: 1 },
    { id: 490, name: "Annatto / Bixin / Norbixin / E160b", category: "Food Additives", rank: 2 },
    { id: 491, name: "Apocarotenal / E160e", category: "Food Additives", rank: 5 },
    { id: 492, name: "Ascorbic acid / E300", category: "Food Additives", rank: 0 },
    { id: 493, name: "Azorubin S / E12 / Brillantcarmoisin O / E122", category: "Food Additives", rank: 2 },
    { id: 494, name: "Baking Soda / Sodium Hydrogen Carbonate / Sodium Bicarbonade", category: "Food Additives", rank: 0 },
    { id: 495, name: "Beeswax / E901", category: "Food Additives", rank: 0 },
    { id: 496, name: "Benzoates / E210, E211, E212, E213", category: "Food Additives", rank: 2 },
    { id: 497, name: "Benzoic Acide / E210", category: "Food Additives", rank: 2 },
    { id: 498, name: "Betanin / Beetroot Red / E162", category: "Food Additives", rank: 0 },
    { id: 499, name: "Bixin / Norbixin / E160b", category: "Food Additives", rank: 5 },
    { id: 500, name: "Borax / Sodium Borate / Sodium Tetraborate / Disodium Tatraborate / E285", category: "Food Additives", rank: 5 },
    { id: 501, name: "Boric Acid / E284", category: "Food Additives", rank: 5 },
    { id: 502, name: "Brilliant Black BN / E151", category: "Food Additives", rank: 3 },
    { id: 503, name: "Brilliant Blue FCF / E133 / Xylene Blue VSG", category: "Food Additives", rank: 5 },
    { id: 504, name: "Brown FK / E154", category: "Food Additives", rank: 2 },
    { id: 505, name: "Brown HT / E155", category: "Food Additives", rank: 2 },
    { id: 506, name: "Butylated hydroxyanisole / E320", category: "Food Additives", rank: 2 },
    { id: 507, name: "Butylated hydroxytoluene / BHT / dibutylhydroxytoluene / E321", category: "Food Additives", rank: 2 },
    { id: 508, name: "CI 14720 / E122", category: "Food Additives", rank: 2 },
    { id: 509, name: "CI 16255 / E124", category: "Food Additives", rank: 2 },
    { id: 510, name: "CI 47005 / E104", category: "Food Additives", rank: 3 },
    { id: 511, name: "Acid Red 18 / E124", category: "Food Additives", rank: 2 },
    { id: 512, name: "Calcium Acetate / Calcium Ethanoate / Calcium Diacetate / E262", category: "Food Additives", rank: 0 },
    { id: 513, name: "Calcium Alginate / E404", category: "Food Additives", rank: 2 },
    { id: 514, name: "Calcium Ascorbate / Calcium Diascorbate", category: "Food Additives", rank: 0 },
    { id: 515, name: "Calcium Benzoate / E213", category: "Food Additives", rank: 2 },
    { id: 516, name: "Calcium Bisulfite / E227", category: "Food Additives", rank: 2 },
    { id: 517, name: "Calcium Carbonate / Limestone / E170", category: "Food Additives", rank: 0 },
    { id: 518, name: "Calcium Citrate / E333", category: "Food Additives", rank: 1 },
    { id: 519, name: "Calcium Diglutamate / E623", category: "Food Additives", rank: 2 },
    { id: 520, name: "Calcium Lactate / E327", category: "Food Additives", rank: 0 },
    { id: 521, name: "Calcium L-ascorbate", category: "Food Additives", rank: 0 },
    { id: 522, name: "Calcium Polyphosphate / E452", category: "Food Additives", rank: 2 },
    { id: 523, name: "Calcium propanoate / Calcium propionate / E282", category: "Food Additives", rank: 5 },
    { id: 524, name: "Calcium Sorbate / E203", category: "Food Additives", rank: 2 },
    { id: 525, name: "Calcium Sulfite / E226", category: "Food Additives", rank: 2 },
    { id: 526, name: "Canthaxanthin / Cantaxanthin / Cantaxanthine / Canthaxanthine / E161g", category: "Food Additives", rank: 5 },
    { id: 527, name: "Caramel color / E150", category: "Food Additives", rank: 0 },
    { id: 528, name: "Carbonated drinks / Carbonic acid", category: "Food Additives", rank: 1 },
    { id: 529, name: "Carboxymethyl cellulose / CMC / carboxymethylcellulose / carmellose / cellulose gum / E466", category: "Food Additives", rank: 5 },
    { id: 530, name: "Carmine / E120", category: "Food Additives", rank: 2 },
    { id: 531, name: "Carmoisine / E122 / Food Red 3 / E122", category: "Food Additives", rank: 2 },
    { id: 532, name: "Carob / Carob Powder / Carob Pod Meal / E410", category: "Food Additives", rank: 2 },
    { id: 533, name: "Carotene / beta-Carotene / E160a", category: "Food Additives", rank: 0 },
    { id: 534, name: "Carrageenan / Processed Seaweed / E407 / E407a", category: "Food Additives", rank: 2 },
    { id: 535, name: "Caustic Caramel / E150a", category: "Food Additives", rank: 0 },
    { id: 536, name: "Caustic Sulphite Caramel / E150b", category: "Food Additives", rank: 0 },
    { id: 537, name: "Cellulose ethyl ether / Ethyl Cellulose / Ethylcellulose / E462", category: "Food Additives", rank: 0 },
    { id: 538, name: "Cellulose methyl ether / Methyl cellulose / methylcellulose / methylated cellulose / E461", category: "Food Additives", rank: 0 },
    { id: 539, name: "Cellulose / E460", category: "Food Additives", rank: 0 },
    { id: 540, name: "Charcoal / E153", category: "Food Additives", rank: 0 },
    { id: 541, name: "Chlorophyll / E140", category: "Food Additives", rank: 0 },
    { id: 542, name: "Citric Acid / E330", category: "Food Additives", rank: 1 },
    { id: 543, name: "Cochineal Red A / E124", category: "Food Additives", rank: 2 },
    { id: 544, name: "Cochineal / E120", category: "Food Additives", rank: 2 },
    { id: 545, name: "Copper complexes of chlorophylls and chlorophyllins / E141", category: "Food Additives", rank: 0 },
    { id: 546, name: "Cream of Tartar / E336", category: "Food Additives", rank: 0 },
    { id: 547, name: "Crimson Lake / E120", category: "Food Additives", rank: 2 },
    { id: 548, name: "Crystal Gum / Karaya Gum / E416", category: "Food Additives", rank: 1 },
    { id: 549, name: "Curcumin / E100", category: "Food Additives", rank: 0 },
    { id: 550, name: "Delta-tocopherol / Vitamin E / E309", category: "Food Additives", rank: 0 },
    { id: 551, name: "Dicalcium Phosphate / Dicalcium Hydrogen Orthophosphate / E340", category: "Food Additives", rank: 1 },
    { id: 552, name: "Dimethicone / Dimethylpolysiloxane / Polydimethylsiloxane / PDMS / E900", category: "Food Additives", rank: 5 },
    { id: 553, name: "Dimethyl dicarbonate / DMDC / Methoxycarbonyl methyl carbonate / Dimethyl pyrocarbonate / Velcorin / E242", category: "Food Additives", rank: 5 },
    { id: 554, name: "Dipotassium phosphate / Dipotassium hydrogen orthophosphate / E340", category: "Food Additives", rank: 1 },
    { id: 555, name: "D-isoascorbate / Sodium erythorbate / Erythorbic acid sodium salt / E316 / Erythorbic acid sodium salt / Sodium erythorbate / D-isoascorbate / E316", category: "Food Additives", rank: 0 },
    { id: 556, name: "E100 / Curcumin", category: "Food Additives", rank: 0 },
    { id: 557, name: "E101a / Riboflavin-5-phosphate", category: "Food Additives", rank: 0 },
    { id: 558, name: "E102 / Tartrazine", category: "Food Additives", rank: 3 },
    { id: 559, name: "E104 / Quinoline Yellow", category: "Food Additives", rank: 3 },
    { id: 560, name: "D110 / Sunset Yellow FCF", category: "Food Additives", rank: 3 },
    { id: 561, name: "E1103 / nvertase / Saccharase / Glucosucrase / beta-h-fructosidase / beta-fructosidase / Invertin / Sucrase", category: "Food Additives", rank: 0 },
    { id: 562, name: "E1105 / Lysozymes", category: "Food Additives", rank: 5 },
    { id: 563, name: "E120 / Carmine / Cochineal", category: "Food Additives", rank: 2 },
    { id: 564, name: "E1200 / Polydextrose", category: "Food Additives", rank: 5 },
    { id: 565, name: "E1201 / Polyvinylpyrrolidone / PVP / Polyvidone / Povidone", category: "Food Additives", rank: 1 },
    { id: 566, name: "E1202 / Polyvinylpolypyrrolidone", category: "Food Additives", rank: 1 },
    { id: 567, name: "E122 / Azourbine / Carmoisine", category: "Food Additives", rank: 1 },
    { id: 568, name: "E123 / Amaranth", category: "Food Additives", rank: 2 },
    { id: 569, name: "E124 / Ponceau 4R / Cochineal Red A", category: "Food Additives", rank: 2 },
    { id: 570, name: "E127 / Erythrosine", category: "Food Additives", rank: 3 },
    { id: 571, name: "E129 / Allura Red / Food Red 17 / CI 16035 / FD&C Red 40, 2-Naphthalenesulfonic acid", category: "Food Additives", rank: 2 },
    { id: 572, name: "E131 / Patent Blue V", category: "Food Additives", rank: 2 },
    { id: 573, name: "E132 / Indigo Carmine / Indigotine", category: "Food Additives", rank: 2 },
    { id: 574, name: "E133 / Brilliant Blue FCF / FD&C Blue No. 1 / Acid Blue 9 / D&C Blue No. 4 / Alzen Food Blue No. 1 / Atracid Blue FG / Erioglaucine / Eriosky blue / Patent Blue AR / Xylene Blue VSG / CI 42090", category: "Food Additives", rank: 5 },
    { id: 575, name: "E140 / Chlorophyll", category: "Food Additives", rank: 0 },
    { id: 576, name: "E141", category: "Food Additives", rank: 0 },
    { id: 577, name: "E142 / Green S / Food Green S / FD&C Green 4 / Acid Green 50 / Lissamine Green B / Wool Green S / CI 44090", category: "Food Additives", rank: 5 },
    { id: 578, name: "E150 / Plain Caramel / Caustic Caramel / Caramel Coloring", category: "Food Additives", rank: 0 },
    { id: 579, name: "E150b / Sulphite-caramel", category: "Food Additives", rank: 0 },
    { id: 580, name: "E150C / Ammonia Caramel", category: "Food Additives", rank: 0 },
    { id: 581, name: "E150D / Sulphite Ammonia Caramel", category: "Food Additives", rank: 0 },
    { id: 582, name: "E151 / Brilliant Black BN / Brilliant Black PN / Brilliant Black A / Black PN / Food Black 1 / Naphthol Black / CI Food Black 1 / CI 28440", category: "Food Additives", rank: 3 },
    { id: 583, name: "E153 / Charcoal", category: "Food Additives", rank: 0 },
    { id: 584, name: "E154 / Brown FK / Kipper Brown / Chocolate Brown FK / CI Food Brown 1", category: "Food Additives", rank: 2 },
    { id: 585, name: "E155 / Brown HT / Chocolate Brown HT / Food Brown 3 / CI 20285", category: "Food Additives", rank: 2 },
    { id: 586, name: "E160a / Carotene / beta-carotene", category: "Food Additives", rank: 0 },
    { id: 587, name: "E160b / Bixin / Norbixin / Annatto", category: "Food Additives", rank: 2 },
    { id: 588, name: "E160d / Lycopene", category: "Food Additives", rank: 5 },
    { id: 589, name: "E160e / Apocarotenal / CI Food Orange 6", category: "Food Additives", rank: 5 },
    { id: 590, name: "E160f / Food Orange 7", category: "Food Additives", rank: 5 },
    { id: 591, name: "E161b / Lutein / Luteine", category: "Food Additives", rank: 5 },
    { id: 592, name: "E161g / Canthaxanthin / Cantaxanthin / Cantaxanthine / Canthaxanthine / Lucantin red (BASF) / Lucantin Red CWD / Carophyll Red / Roxanthin Red 10 / L-Orange 7g / CI Food Orange 8", category: "Food Additives", rank: 5 },
    { id: 593, name: "E162 / Betanin / Beetroot Red", category: "Food Additives", rank: 0 },
    { id: 594, name: "E163 / Anthocyanins / Anthocyans", category: "Food Additives", rank: 0 },
    { id: 595, name: "E170 / Calcium Carbonate / Limestone / Calcite / Aragonite / Chalk", category: "Food Additives", rank: 0 },
    { id: 596, name: "E171 / Titanium dioxide / Titanium oxide / Titania / Oxide of Titanium / Titanium White / Pigment White 6 (PW6) / CI 77891", category: "Food Additives", rank: 0 },
    { id: 597, name: "E172 / Iron Oxides", category: "Food Additives", rank: 0 },
    { id: 598, name: "E173 / Aluminium", category: "Food Additives", rank: 5 },
    { id: 599, name: "E174 / Silver", category: "Food Additives", rank: 5 },
    { id: 600, name: "E175 / Gold", category: "Food Additives", rank: 0 },
    { id: 601, name: "E180 / Lithol Rubine BK / Pigment Rubine / Carmine 6B / Brilliant Carmine 6B / Permanent Rubin L6B / Litholrubine / Latolrubine / CI Pigment Red 57 / CI Pigment Red 57:1 / D&C Red No. 7 / CO 15850:1", category: "Food Additives", rank: 2 },
    { id: 602, name: "E200 / Sorbic Acid", category: "Food Additives", rank: 2 },
    { id: 603, name: "E202 / Potassium Sorbate", category: "Food Additives", rank: 2 },
    { id: 604, name: "E203 / Calcium Sorbate", category: "Food Additives", rank: 2 },
    { id: 605, name: "E210 / Benzoic Acid", category: "Food Additives", rank: 2 },
    { id: 606, name: "E210-213 / Benzoic Acid & Salts = Benzoates", category: "Food Additives", rank: 2 },
    { id: 607, name: "E211 / Sodium Benzoate", category: "Food Additives", rank: 2 },
    { id: 608, name: "E212 / Potassium Benzoate", category: "Food Additives", rank: 2 },
    { id: 609, name: "E213 / Calcium Benzoate", category: "Food Additives", rank: 2 },
    { id: 610, name: "E214 / E215 / Ethylparaben / Ethyl para-hydroxybenzoate", category: "Food Additives", rank: 2 },
    { id: 611, name: "E218 / E219 / Methylparaben", category: "Food Additives", rank: 2 },
    { id: 612, name: "E220 / Sulphur dioxide", category: "Food Additives", rank: 2 },
    { id: 613, name: "E221 / sodium Sulfite", category: "Food Additives", rank: 2 },
    { id: 614, name: "E222 / Sodium Hydrogen Sulphite / Sodium bisulphite", category: "Food Additives", rank: 2 },
    { id: 615, name: "E223 / Sodium Metabisulfite", category: "Food Additives", rank: 2 },
    { id: 616, name: "E224 / Potassium Metabisulfite", category: "Food Additives", rank: 2 },
    { id: 617, name: "E225 / Potassium Sulfite", category: "Food Additives", rank: 2 },
    { id: 618, name: "E226 / Calcium Sulfite", category: "Food Additives", rank: 2 },
    { id: 619, name: "E227 / Calcium Bisulfite", category: "Food Additives", rank: 2 },
    { id: 620, name: "E228 / Potassium hydrogen sulfite", category: "Food Additives", rank: 2 },
    { id: 621, name: "E231 / Orthophenyl phenol", category: "Food Additives", rank: 2 },
    { id: 622, name: "E232 / sodium orthophenyl phenol", category: "Food Additives", rank: 2 },
    { id: 623, name: "E234 / Nisin", category: "Food Additives", rank: 5 },
    { id: 624, name: "E235 / Natamycin / Pimaricin / Natacyn", category: "Food Additives", rank: 5 },
    { id: 625, name: "E239 / Hexamethylenetetramin / Hexamine / Methenamine / Urotropine 1, 3, 5 & 7 / Formin / Aminoform", category: "Food Additives", rank: 2 },
    { id: 626, name: "E242 / Dimethyl dicarbonate / DMDC / Methoxycarbonyl methyl carbonate / Dimethyl pyrocarbonate / Velcorin", category: "Food Additives", rank: 5 },
    { id: 627, name: "E249 / Potassium Nitrite", category: "Food Additives", rank: 5 },
    { id: 628, name: "E250 / Sodium Nitrite", category: "Food Additives", rank: 0 },
    { id: 629, name: "E251 / Sodium Nitrate", category: "Food Additives", rank: 5 },
    { id: 630, name: "E252 / Potassium Nitrate / Saltpeter / Nitrate of Potash", category: "Food Additives", rank: 5 },
    { id: 631, name: "E260 / Acetic Acid", category: "Food Additives", rank: 0 },
    { id: 632, name: "E261 / Potassium Acetate", category: "Food Additives", rank: 0 },
    { id: 633, name: "E262 / Sodium Acetate / Sodium Ethanoate", category: "Food Additives", rank: 0 },
    { id: 634, name: "E263 / Calcium Acetate / Acetate of Lime / Calcium Ethanoate / Calcium diacetate", category: "Food Additives", rank: 0 },
    { id: 635, name: "E270 / Lactic Acid / Milk Acid / 2-hydroxypropanoic acid", category: "Food Additives", rank: 0 },
    { id: 636, name: "E280 / Propionic Acid / Propanoic Acid", category: "Food Additives", rank: 5 },
    { id: 637, name: "E281 / sodium Propanoate / Sodium Propionate", category: "Food Additives", rank: 5 },
    { id: 638, name: "E282 / Calcium Propanoate / Calcium Propionate", category: "Food Additives", rank: 5 },
    { id: 639, name: "E283 / Potassium Propanoate / Potassium Propionate", category: "Food Additives", rank: 5 },
    { id: 640, name: "E284 / Boric Acid", category: "Food Additives", rank: 5 },
    { id: 641, name: "E285 / Borax / Sodium Borate / Sodium tetraborate / Disodium tetraborate", category: "Food Additives", rank: 5 },
    { id: 642, name: "E290 / Carbon Dioxide / Carbonic Acid Gas / Carbonic Anhydride / Carbonic Oxide", category: "Food Additives", rank: 0 },
    { id: 643, name: "E296 / Malic Acid / Hydroxybutanedioic acid", category: "Food Additives", rank: 0 },
    { id: 644, name: "E297 / Fumaric Acid / Trans-butenedioic acid / Allomaleic acid / Boletic Acid / Donitic Acid / Lichenic Acid", category: "Food Additives", rank: 5 },
    { id: 645, name: "E300 / Ascorbic Acid / Vitamin C", category: "Food Additives", rank: 0 },
    { id: 646, name: "E301 / Sodium Ascorbate / Sodascorbate", category: "Food Additives", rank: 0 },
    { id: 647, name: "E302 / Calcium Ascorbate / Calcium Diascorbate", category: "Food Additives", rank: 0 },
    { id: 648, name: "E304 / Ascorbyl palmitate", category: "Food Additives", rank: 0 },
    { id: 649, name: "E306 / Tocopherol / Vitamin E", category: "Food Additives", rank: 0 },
    { id: 650, name: "E307 / Alpha-tocopherol / Vitamin E", category: "Food Additives", rank: 0 },
    { id: 651, name: "E308 / Gamma-tocopherol / Vitamin E", category: "Food Additives", rank: 0 },
    { id: 652, name: "E309 / Delta-tocopherol / Vitamine E", category: "Food Additives", rank: 0 },
    { id: 653, name: "E310 / Propyl gallate / Propyl 3,4,5-trihydroxybenzoate / Gallic acid propylester", category: "Food Additives", rank: 2 },
    { id: 654, name: "E311 / Octyl Gallate", category: "Food Additives", rank: 2 },
    { id: 655, name: "E312 / Dodecyl Galate / Lauryl Gallate", category: "Food Additives", rank: 2 },
    { id: 656, name: "E315 / Erythorbic Acid / Isoascorbic Acid / D-araboascorbic Acid", category: "Food Additives", rank: 0 },
    { id: 657, name: "E316 / Sodium Erythorbate / D-isoascorbate / Erythorbic acid", category: "Food Additives", rank: 0 },
    { id: 658, name: "E319 / tert-Butylhydroquinone / TBHQ", category: "Food Additives", rank: 5 },
    { id: 659, name: "E320 / Butylated hydroxyanisole", category: "Food Additives", rank: 2 },
    { id: 660, name: "E321 / Butylated hydroxytoluene / BHT / dibutylhydroxytoluene", category: "Food Additives", rank: 2 },
    { id: 661, name: "E322 / Lecithins / Lecithin", category: "Food Additives", rank: 0 },
    { id: 662, name: "E325 / Sodium Lactate", category: "Food Additives", rank: 0 },
    { id: 663, name: "E326 / Potassium Lactate", category: "Food Additives", rank: 0 },
    { id: 664, name: "E327 / Calcium Lactate", category: "Food Additives", rank: 0 },
    { id: 665, name: "E330 / Citric Acid", category: "Food Additives", rank: 1 },
    { id: 666, name: "E331 / Trisodium Citrate / Sodium Citrate / Citric Acid Trisodium Salt", category: "Food Additives", rank: 1 },
    { id: 667, name: "E332 / Potassium Citrate / Tripotassium Citrate", category: "Food Additives", rank: 1 },
    { id: 668, name: "E333 / Calcium Citrate / Tricalcium Dicitrate", category: "Food Additives", rank: 1 },
    { id: 669, name: "E334 / Tartaric Acid / 2,3-dihydroxybutanedioic acid / 2,3-dihydroxysuccinic acid / Threaric Acid / Racemic Acid / Uvic Acid / Paratartaric Acid", category: "Food Additives", rank: 0 },
    { id: 670, name: "E335 / Sodium Tartrate / Sal Tartar / Disodium tartrate / Bisodium tartrate / Monosodium tartrate / Sodium bitartrate", category: "Food Additives", rank: 0 },
    { id: 671, name: "E336 / Cream of Tartar / Postassium bitartrate", category: "Food Additives", rank: 0 },
    { id: 672, name: "E340 / Calcium Phosphates: monocalcium phosphate (KH2PO4 / Calcium dihydrogen phospate) / dicalcim phosphate (K2HPO4) / Tricalcium phosphate (K3PO4)", category: "Food Additives", rank: 1 },
    { id: 673, name: "E380 / Ammonium Citrate / Triammonium Citrate", category: "Food Additives", rank: 1 },
    { id: 674, name: "E400 / Alginic Acid / Algin / Alginate", category: "Food Additives", rank: 2 },
    { id: 675, name: "E401 / Sodium Alginate", category: "Food Additives", rank: 2 },
    { id: 676, name: "E402 / Potassium Alginate", category: "Food Additives", rank: 2 },
    { id: 677, name: "E403 / Ammonium Alginate", category: "Food Additives", rank: 2 },
    { id: 678, name: "E404 / Calcium Alginate", category: "Food Additives", rank: 2 },
    { id: 679, name: "E405 / Propylene glycolic alginate", category: "Food Additives", rank: 2 },
    { id: 680, name: "E406 / Agar", category: "Food Additives", rank: 1 },
    { id: 681, name: "E407 / E407a / Carrageenan / Processed Seaweed", category: "Food Additives", rank: 2 },
    { id: 682, name: "E410 / Locust Bean Gum / LGB / Carobin / Carob Bean Gum", category: "Food Additives", rank: 2 },
    { id: 683, name: "E412 / Guar Gum / Guaran", category: "Food Additives", rank: 2 },
    { id: 684, name: "E413 / Tragacanth", category: "Food Additives", rank: 2 },
    { id: 685, name: "E414 / Gum Arabic / Acacia Gum / Chaar Gund / Char Goond / Meska", category: "Food Additives", rank: 1 },
    { id: 686, name: "E415 / Xanthan Gum", category: "Food Additives", rank: 0 },
    { id: 687, name: "E416 / Gum Karaya / Karaya Gum / Crystal Gum", category: "Food Additives", rank: 1 },
    { id: 688, name: "E421 / Mannitol / Mannite / Manna Sugar", category: "Food Additives", rank: 0 },
    { id: 689, name: "E422 / Glycerol / Glycerine / Glycerin / Propanetriol", category: "Food Additives", rank: 0 },
    { id: 690, name: "E440 / Pectin", category: "Food Additives", rank: 0 },
    { id: 691, name: "E441 / Gelatin", category: "Food Additives", rank: 0 },
    { id: 692, name: "E452", category: "Food Additives", rank: 2 },
    { id: 693, name: "E460 / Cellulose", category: "Food Additives", rank: 0 },
    { id: 694, name: "E461 / Methyl Cellulose", category: "Food Additives", rank: 0 },
    { id: 695, name: "E462 / Ethyl Cellulose", category: "Food Additives", rank: 0 },
    { id: 696, name: "E463 / Hydroxypropylcelulose", category: "Food Additives", rank: 0 },
    { id: 697, name: "E464 / Hypromellose", category: "Food Additives", rank: 0 },
    { id: 698, name: "E465 / Ethyl methyl cellulose", category: "Food Additives", rank: 0 },
    { id: 699, name: "E466 / Carboxymethyl cellulose", category: "Food Additives", rank: 5 },
    { id: 700, name: "E500i / Sodium Carbonate", category: "Food Additives", rank: 0 },
    { id: 701, name: "E500ii / Sodium Hydrogen Carbonate", category: "Food Additives", rank: 0 },
    { id: 702, name: "E501 / Potassium Carbonate", category: "Food Additives", rank: 0 },
    { id: 703, name: "E503 / Ammonium Carbonate", category: "Food Additives", rank: 0 },
    { id: 704, name: "E504 / Magnesium Carbonate", category: "Food Additives", rank: 0 },
    { id: 705, name: "E507 / Hydrochloric Acid", category: "Food Additives", rank: 0 },
    { id: 706, name: "E579 / Iron(II) Gluconate", category: "Food Additives", rank: 0 },
    { id: 708, name: "E620 / Glutamic Acid", category: "Food Additives", rank: 2 },
    { id: 709, name: "E621 / Monosodium glutamate", category: "Food Additives", rank: 2 },
    { id: 710, name: "E622 / Potassium glutamate", category: "Food Additives", rank: 2 },
    { id: 711, name: "E623 / Calcium Diglutamate", category: "Food Additives", rank: 2 },
    { id: 712, name: "E624 / Monoamonium glutamate", category: "Food Additives", rank: 2 },
    { id: 713, name: "E625 / Magnesium diglutamate", category: "Food Additives", rank: 2 },
    { id: 714, name: "E626 / Guanosine monophosphate", category: "Food Additives", rank: 0 },
    { id: 715, name: "E650 / Zinc Acetate", category: "Food Additives", rank: 0},
    { id: 716, name: "E900 / Polydimethylsiloxane", category: "Food Additives", rank: 0 },
    { id: 717, name: "E901 / Beeswax", category: "Food Additives", rank: 0 },
    { id: 718, name: "E955 / Sucraose", category: "Food Additives", rank: 0 },
    { id: 719, name: "E960 / Steviol Glycosides", category: "Food Additives", rank: 0 },
    { id: 720, name: "E127 / Erythrosine", category: "Food Additives", rank: 3 },
    { id: 721, name: "E462 / Ethylcellulose", category: "Food Additives", rank: 0 },
    { id: 722, name: "E465 / Ethyl methyl cellulose", category: "Food Additives", rank: 0 },  
    { id: 723, name: "E214 / E215 / Ethylparaben", category: "Food Additives", rank: 0 },
    { id: 724, name: "Ferrous Gluconate / Iron(II) Gluconate / E579", category: "Food Additives", rank: 0 },
    { id: 725, name: "Fizzy Drinks", category: "Food Additives", rank: 1 },
    { id: 726, name: "Flavin Mononucleotide / E101a", category: "Food Additives", rank: 1 },
    { id: 727, name: "Flavor enhancers / glutamates / E620, E621, E622, E623, E624, E625", category: "Food Additives", rank: 2 },
    { id: 728, name: "Flavorings", category: "Food Additives", rank: 1 },
    { id: 729, name: "Food Orange 7 / E160f", category: "Food Additives", rank: 5 },
    { id: 730, name: "Food Yellow 13 / E104", category: "Food Additives", rank: 3 },
    { id: 731, name: "Fumaric acid / Trans-butenedioic acid / E297", category: "Food Additives", rank: 5 },
    { id: 732, name: "Gamma-tocopherol / Vitamin E / E308", category: "Food Additives", rank: 0 },
    { id: 733, name: "Gelatin / E41", category: "Food Additives", rank: 1 },
    { id: 734, name: "Gluten", category: "Food Additives", rank: 1 },
    { id: 735, name: "glycerol / Glycerine / Glycerin / E422", category: "Food Additives", rank: 0 },
    { id: 736, name: "Gold / E175", category: "Food Additives", rank: 0 },
    { id: 737, name: "Green S / E142 / Food Green S / FD&C Green 4 / Acid Green 50  /Lissamine Green B / Wool Green S / CI 44090", category: "Food Additives", rank: 5 },
    { id: 738, name: "Guanosine monophosphate / 5'-guanidylic acid / Guanylic Acid / E626", category: "Food Additives", rank: 0 },
    { id: 739, name: "Guar Gum / Guaran / E412", category: "Food Additives", rank: 1 },
    { id: 740, name: "Gum Arabic / Acacia Gum / E414", category: "Food Additives", rank: 1 },
    { id: 741, name: "Gum Karaya / Karaya Gum / Crystal Gum / E416", category: "Food Additives", rank: 1 },
    { id: 742, name: "Hemicalcium ascorbate / E302", category: "Food Additives", rank: 0 },
    { id: 743, name: "Hexamethylenetetramine / Hexamine / Methenamine / Urotropine 1, 3, 5, 7 / Tetraazaadamantane / Formin / Aminoform", category: "Food Additives", rank: 2 },
    { id: 744, name: "Hydrochloric Acid / E507", category: "Food Additives", rank: 0 },
    { id: 745, name: "Hydroxypropylcellulose / E463", category: "Food Additives", rank: 0 },
    { id: 746, name: "Hypromellose / Hydroxypropyl methylcellulose / Hydroxypropyl methyl cellulose / HPMC / E464", category: "Food Additives", rank: 0 },
    { id: 747, name: "Indigo carmine / Indigotine / E132", category: "Food Additives", rank: 2 },
    { id: 748, name: "Invertase / E1103", category: "Food Additives", rank: 0 },
    { id: 749, name: "Iron Oxides / E172", category: "Food Additives", rank: 0 },
    { id: 750, name: "Iron(II) gluconate / Ferrous gluconate / E579", category: "Food Additives", rank: 0 },
    { id: 751, name: "Karaya Gum / Gum Karaya / Crystal Gum / E416", category: "Food Additives", rank: 1 },
    { id: 752, name: "Lactic Acid / Milk Acid / 2-hydroxypropanoic acid / E270", category: "Food Additives", rank: 0 },
    { id: 753, name: "Lecithins / Lecithin / E322", category: "Food Additives", rank: 0 },
    { id: 754, name: "Lithol Rubine BK / E180", category: "Food Additives", rank: 2 },
    { id: 755, name: "Locust Bean Gum / LBG / E410", category: "Food Additives", rank: 2 },
    { id: 756, name: "Lutein / Luteine / E161b", category: "Food Additives", rank: 5 },
    { id: 757, name: "Lycopene / E160d", category: "Food Additives", rank: 5 },
    { id: 758, name: "Lysozymes / E1105", category: "Food Additives", rank: 5 },
    { id: 759, name: "Magnesium carbonate / E504", category: "Food Additives", rank: 0 },
    { id: 760, name: "Magnesium diglutamate / Magnesium glutamate / E625", category: "Food Additives", rank: 2 },
    { id: 761, name: "Malic Acid / Hydroxybutanedioic acid / E296", category: "Food Additives", rank: 0 },
    { id: 762, name: "Mannitol / Mannite / E421", category: "Food Additives", rank: 0 },
    { id: 763, name: "Methyl cellulose / Methylcellulose / Methylated cellulose / Cellulose methyl ether / E461", category: "Food Additives", rank: 0 },
    { id: 764, name: "Methyl ethyl cellulose / Ethyl methyl cellulose / E465", category: "Food Additives", rank: 0 },
    { id: 765, name: "Methylparaben / E218 / E219", category: "Food Additives", rank: 2 },
    { id: 766, name: "Monoammonium glutamate / Ammonium glutamate / Glutamic acid ammonium salt / E624", category: "Food Additives", rank: 2 },
    { id: 767, name: "Monocalcium phosphate / E340", category: "Food Additives", rank: 1 },
    { id: 768, name: "Monopotassium phospate / E340", category: "Food Additives", rank: 1 },
    { id: 769, name: "Monosodium ascorbate / E301", category: "Food Additives", rank: 0 },
    { id: 770, name: "Monosodium glutamate / E621", category: "Food Additives", rank: 2 },
    { id: 771, name: "Natamycine / Natacyn / Pimaricin / E235", category: "Food Additives", rank: 5 },
    { id: 772, name: "Nisin / E234", category: "Food Additives", rank: 5 },
    { id: 773, name: "Norbixin / Bixin / Annatto / E160b", category: "Food Additives", rank: 2 },
    { id: 774, name: "Octyl gallate / E311", category: "Food Additives", rank: 2 },
    { id: 775, name: "Orange Yellow S / E110", category: "Food Additives", rank: 3 },
    { id: 776, name: "Orthophenyl phenol / E231", category: "Food Additives", rank: 2 },
    { id: 777, name: "Parabens / PHB-ester / E214, E215, E216, E217, E218, E219 / para-hydroxy-benzoic acid = PHB", category: "Food Additives", rank: 2 },
    { id: 778, name: "Patent blue V / E131", category: "Food Additives", rank: 2 },
    { id: 779, name: "Pectin / E440", category: "Food Additives", rank: 0 },
    { id: 780, name: "Pimaricin / Natamycine / E235", category: "Food Additives", rank: 5 },
    { id: 781, name: "Plain caramel / E150a", category: "Food Additives", rank: 0 },
    { id: 782, name: "Polydextrose / E1200", category: "Food Additives", rank: 5 },
    { id: 783, name: "Polydimethylsiloxane / PDMS / Dimethicone / Dimethylpolysiloxane / E900", category: "Food Additives", rank: 5 },
    { id: 784, name: "Polyvinylpolypyrrolidone / E1202", category: "Food Additives", rank: 1 },
    { id: 785, name: "Polyvinylpyrrolidone / PVP / Polyvidone / Povidone / E1201", category: "Food Additives", rank: 1 },
    { id: 786, name: "Ponceau 4R / E124", category: "Food Additives", rank: 2 },
    { id: 787, name: "Potassium acetate / E261", category: "Food Additives", rank: 0 },
    { id: 788, name: "Potassium alginate / E402", category: "Food Additives", rank: 2 },
    { id: 789, name: "Potassium benzoate / E212", category: "Food Additives", rank: 2 },
    { id: 790, name: "Potassium bitartrate / E336", category: "Food Additives", rank: 0 },
    { id: 791, name: "Potassium carbonate / Carbonate of potash / E501", category: "Food Additives", rank: 0 },
    { id: 792, name: "Potassium citrate / Tripotassium citrate / E332", category: "Food Additives", rank: 1 },
    { id: 793, name: "Potassium glutamate / Glutamic acid potassium salt / E622", category: "Food Additives", rank: 2 },
    { id: 794, name: "Potassium hydrogen sulfite / Potassium bisulfite / E228", category: "Food Additives", rank: 2 },
    { id: 795, name: "Potassium hydrogen tartrate / E336", category: "Food Additives", rank: 0 },
    { id: 796, name: "Potassium lactate / E326", category: "Food Additives", rank: 0 },
    { id: 797, name: "Potassium metavisulfite / E224", category: "Food Additives", rank: 2 },
    { id: 798, name: "Potassium nitrite / E249", category: "Food Additives", rank: 5 },
    { id: 799, name: "Potassium polyphosphate / E452", category: "Food Additives", rank: 2 },
    { id: 800, name: "Potassium propanoate / Potassium propionate / E283", category: "Food Additives", rank: 5 },
    { id: 881, name: "Potassium pyrosulfite / E224", category: "Food Additives", rank: 2 },
    { id: 882, name: "Potassium sorbate / E202", category: "Food Additives", rank: 2 },
    { id: 883, name: "Potassium sulfite / E225", category: "Food Additives", rank: 2 },
    { id: 884, name: "Povidone / Polyvidone / Polyvinylpyrroolidone / PVP / E1201", category: "Food Additives", rank: 1 },
    { id: 885, name: "Propionic Acid / Propanoic Acid / E280", category: "Food Additives", rank: 2 },
    { id: 886, name: "Propyl gallate / E310", category: "Food Additives", rank: 2 },
    { id: 887, name: "Propylene glycolic alginate / E405", category: "Food Additives", rank: 2 },
    { id: 888, name: "Quinine (eg. in Bitter Lemon or Tonic Water", category: "Food Additives", rank: 2 },
    { id: 889, name: "Quinoline yellow / E104", category: "Food Additives", rank: 3 },
    { id: 890, name: "Red 2G / Acid red 1 / Azogeranine / Azohpoloxine / E128", category: "Food Additives", rank: 2 },
    { id: 891, name: "Riboflavin-5'-phosphate / E101a", category: "Food Additives", rank: 1 },
    { id: 892, name: "Saliylic Acid", category: "Food Additives", rank: 2 },
    { id: 893, name: "Silver / E174", category: "Food Additives", rank: 5 },
    { id: 894, name: "Sodascorbate / Sodium ascorbate / Monosodium ascorbate / E301", category: "Food Additives", rank: 0 },
    { id: 895, name: "sodium acetate / E262", category: "Food Additives", rank: 0 },
    { id: 896, name: "Sodium alginate / E401", category: "Food Additives", rank: 2 },
    { id: 897, name: "Sodium ascorbate / Sodascorbate", category: "Food Additives", rank: 0 },
    { id: 898, name: "Sodium benzoate / E211", category: "Food Additives", rank: 2 },
    { id: 899, name: "Sodium bisulphite / E222", category: "Food Additives", rank: 2 },
    { id: 900, name: "Sodium carbonate / Washing soda / Soda ash / Soda crystals / Na2CO3 / E500i", category: "Food Additives", rank: 0 },
    { id: 901, name: "Sodium citrate / Trisodium citrate / E331", category: "Food Additives", rank: 1 },
    { id: 902, name: "Sodium erythorbate / D-isoascorbate / Erythorbic acid sodium salt / E316", category: "Food Additives", rank: 0 },
    { id: 903, name: "Sodium hydrogen carbonate / Sodium bicarbonate / Baking soda / Bicarbonate of soda / E500ii", category: "Food Additives", rank: 0 },
    { id: 904, name: "Sodium hydrogen sulphite / E222", category: "Food Additives", rank: 2 },
    { id: 905, name: "Sodium lactate / E325", category: "Food Additives", rank: 0 },
    { id: 906, name: "Sodium metabisulfite / E223", category: "Food Additives", rank: 2 },
    { id: 907, name: "Sodium nitrate / E251", category: "Food Additives", rank: 5 },
    { id: 908, name: "Sodium nitrite / E250", category: "Food Additives", rank: 0 },
    { id: 909, name: "Sodium orthophenyl phenol / E232", category: "Food Additives", rank: 2 },
    { id: 910, name: "Sodium polyphosphate / E452", category: "Food Additives", rank: 2 },
    { id: 911, name: "Sodium propanoate / Sodium propionate / E281", category: "Food Additives", rank: 5 },
    { id: 912, name: "Sodium pyrosulfite / E223", category: "Food Additives", rank: 2 },
    { id: 913, name: "Sodium sulfite / Sodium sulphite / E221", category: "Food Additives", rank: 2 },
    { id: 914, name: "Sodium tartrate / Sal tartar / Disodium tartrate / Bisodium tartrate / E335", category: "Food Additives", rank: 0 },
    { id: 915, name: "Sodium-calcium polyphosphate / E452", category: "Food Additives", rank: 2 },
    { id: 916, name: "Sorbates (salts of sorbic acid): Potassium sorbate / E202 / Calcium sorbate / E203", category: "Food Additives", rank: 2 },
    { id: 917, name: "Sorbic acid / E200", category: "Food Additives", rank: 2 },
    { id: 918, name: "Starch / Amylum", category: "Food Additives", rank: 0 },
    { id: 919, name: "Steviol glycosides / E960", category: "Food Additives", rank: 0 },
    { id: 920, name: "Sucralose / E955", category: "Food Additives", rank: 0 },
    { id: 921, name: "Sulfites / Sulphites / E220, E221, E222, E223, E224, E225, E226, E227, E228", category: "Food Additives", rank: 2 },
    { id: 921, name: "Sulfur dioxide / Sulphur dioxide / E220", category: "Food Additives", rank: 2 },
    { id: 922, name: "Sulphan blue / E131", category: "Food Additives", rank: 2 },
    { id: 923, name: "Sulphite ammonia caramel / E150d", category: "Food Additives", rank: 0 },
    { id: 924, name: "Sunset yellow FCF / E110", category: "Food Additives", rank: 3 },
    { id: 925, name: "Tartaric acid / Uvic acid / E334", category: "Food Additives", rank: 0 },
    { id: 926, name: "Tartrazine / E102", category: "Food Additives", rank: 3 },
    { id: 927, name: "Tert-Butylhydroquinone / TBHQ / E319", category: "Food Additives", rank: 5 },
    { id: 928, name: "Titanium dioxide / Titanium(IV) oxide / E171", category: "Food Additives", rank: 0 },
    { id: 929, name: "Tocopherol / Vitamin E / E306", category: "Food Additives", rank: 0 },
    { id: 930, name: "Tragacanth / E413", category: "Food Additives", rank: 2 },
    { id: 931, name: "Triammonium citrate / Ammonium citrate / E380", category: "Food Additives", rank: 1 },
    { id: 932, name: "Tricalcium phosphate / E340", category: "Food Additives", rank: 1 },
    { id: 933, name: "Tripotassium citrate / Potassium citrate / E332", category: "Food Additives", rank: 1 },
    { id: 934, name: "Tripotassium phosphate / E340", category: "Food Additives", rank: 1 },
    { id: 935, name: "Trisodium citrate / Sodium citrate / E331", category: "Food Additives", rank: 1 },
    { id: 936, name: "Vanillin (synthetic)", category: "Food Additives", rank: 0 },
    { id: 937, name: "Vitamin C / E300", category: "Food Additives", rank: 0 },
    { id: 938, name: "Vitamin E / Alpha-tocopherol / E307", category: "Food Additives", rank: 0 },
    { id: 939, name: "Vitamin E / Delta-tocopherol / E309", category: "Food Additives", rank: 0 },
    { id: 940, name: "Vitamin E / Gamma-tocopherol / E308", category: "Food Additives", rank: 0 },
    { id: 941, name: "Vitamin E / Tocopherol / E306", category: "Food Additives", rank: 0 },
    { id: 942, name: "Xanthan gum / E415", category: "Food Additives", rank: 0 },
    { id: 943, name: "Zinc acetate / E650", category: "Food Additives", rank: 0 },
    { id: 944, name: "Folic acid / Folate / Vitamin B9", category: "Vitamins, Dietary Minerals, Trace Elements, & Stimulants", rank: 2 },
    { id: 945, name: "Iodine", category: "Vitamins, Dietary Minerals, Trace Elements, & Stimulants", rank: 3 },
    { id: 946, name: "Iodized table salt", category: "Vitamins, Dietary Minerals, Trace Elements, & Stimulants", rank: 2 },
    { id: 947, name: "Potassium iodate (eg, as an additive in iodized table salt", category: "Vitamins, Dietary Minerals, Trace Elements, & Stimulants", rank: 3 },
    { id: 948, name: "Potassium iodide (eg, as an additive in iodized table salt", category: "Vitamins, Dietary Minerals, Trace Elements, & Stimulants", rank: 3 },
    { id: 949, name: "Theobromine", category: "Vitamins, Dietary Minerals, Trace Elements, & Stimulants", rank: 2 },
    { id: 950, name: "Vitamin B9 / Folic acid / Folate", category: "Vitamins, Dietary Minerals, Trace Elements, & Stimulants", rank: 2 },
    { id: 951, name: "Xantheose / Theobromine", category: "Vitamins, Dietary Minerals, Trace Elements, & Stimulants", rank: 2 },
    { id: 952, name: "Liquorice", category: "Preparations & Mixtures", rank: 2 },
    { id: 953, name: "Marzipan", category: "Preparations & Mixtures", rank: 1 },
    { id: 954, name: "Marchpane", category: "Preparations & Mixtures", rank: 1 },
    { id: 955, name: "Chocolate, brown / black", category: "Preparations & Mixtures", rank: 2 },
    { id: 956, name: "Chocolate, white", category: "Preparations & Mixtures", rank: 1 },
    { id: 957, name: "Mustard", category: "Preparations & Mixtures", rank: 2 },
    { id: 958, name: "Tofu", category: "Preparations & Mixtures", rank: 2},

    





    // Keep adding ingredients here
];
// RANK 5 = UNKNOWN TEMP PLACE HOLDER 
